name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group rg-githubactions
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: f8ad2745-edf3-4367-8029-db6162224aec
          region: UK South
          template: ./arm-templates/resourcegroup.json
          parameters:
            location="UK South"
            resourceGroupName=rg-githubactions
          deploymentName: rg-githubactions

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: f8ad2745-edf3-4367-8029-db6162224aec
          template: ./arm-templates/storageaccount.json
          parameters:
             sku=Standard_LRS   
             storageAccountName=globostg003
             location="UK South"
          deploymentMode: incremental  

      - name: Deploy Virtual machine
        uses: Azure/arm-deploy@v1  
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: f8ad2745-edf3-4367-8029-db6162224aec
          template: ./arm-templates/virtualmachine.json
          parameters:
             adminPassword=${{ secrets.UBUNTU_ADMIN_PASSWORD }}
          deploymentMode: incremental  
    